#!/bin/sh
# prepend a JIRA to a commit message automatically
# if amend, don't do anything
if ! [ -z $3 ] ;then
    exit
fi
branch=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
JIRA=$(echo $branch | cut -d / -f2 |cut -d - -f1-2)
KEY_FOUND=$(echo $JIRA | grep '[A-Z]\{1,\}-[0-9]\{1,\}')
if [ -z "$KEY_FOUND" ] ;then        # when task has not been retrieved from branch name, exit
   exit
fi
# enclose JIRA in square brackets
text=[${JIRA}]
file=`cat "$1"`
echo "$text $file" > "$1"
 
